# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv


# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [78]:
import pandas as pd
import numpy as np

In [79]:
data_spec1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [80]:
data_spec1

Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
4003      NaN         NaN    NaN                   NaN   
4004      NaN         NaN    NaN                   NaN   
4005      NaN         NaN    NaN                   NaN   
4006      NaN         NaN    NaN                   NaN   
4007      NaN         NaN    NaN                   NaN   

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
4003                     NaN      NaN                   NaN   
4004                     NaN      NaN                   NaN   
4005                     NaN      NaN                   NaN   
4006                     NaN      NaN                   NaN   
4007                     NaN      NaN                   NaN   

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
4003                       NaN             NaN            NaN   
4004                       NaN             NaN            NaN   
4005                       NaN             NaN            NaN   
4006                       NaN             NaN            NaN   
4007                       NaN             NaN            NaN   

      Total Claim Amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
4003                 NaN  
4004                 NaN  
4005                 NaN  
4006                 NaN  
4007                 NaN  

[4008 rows x 11 columns]

In [81]:
# Standardization of columns names into lower cases
data_spec1.columns = data_spec1.columns.str.lower().str.replace(" ","_")

data_spec1

customer          st gender             education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
4003      NaN         NaN    NaN                   NaN   
4004      NaN         NaN    NaN                   NaN   
4005      NaN         NaN    NaN                   NaN   
4006      NaN         NaN    NaN                   NaN   
4007      NaN         NaN    NaN                   NaN   

     customer_lifetime_value   income  monthly_premium_auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
4003                     NaN      NaN                   NaN   
4004                     NaN      NaN                   NaN   
4005                     NaN      NaN                   NaN   
4006                     NaN      NaN                   NaN   
4007                     NaN      NaN                   NaN   

     number_of_open_complaints     policy_type  vehicle_class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
4003                       NaN             NaN            NaN   
4004                       NaN             NaN            NaN   
4005                       NaN             NaN            NaN   
4006                       NaN             NaN            NaN   
4007                       NaN             NaN            NaN   

      total_claim_amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
4003                 NaN  
4004                 NaN  
4005                 NaN  
4006                 NaN  
4007                 NaN  

[4008 rows x 11 columns]

In [82]:
# Renaming column 
data_spec1 = data_spec1.rename(columns={"st": "state"})

In [83]:
column_names = data_spec1.columns
print(column_names)
# as we can see below in the list of column names the previous column name called st is now state

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')


## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [84]:
data_spec1['gender'].unique()
# Replace inconsistent and incorrect values with "F"

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [85]:
# Replace inconsistent and incorrect values with "F"
data_spec1['gender'] = data_spec1['gender'].replace({"Femal":"F", "female": "F",})


In [86]:
data_spec1['gender'] = data_spec1['gender'].replace({"Male":"M"})
# Replace inconsistent and incorrect values with "F"

In [87]:
gender_counts = data_spec1['gender'].value_counts()

# Display the count for each gender value
for gender, count in gender_counts.items():
    print(f"{gender}: {count}")


F: 502
M: 452


In [88]:
data_spec1['gender'].unique() # looking at the output below we are now sure that the inconsistent values were changed to "F" and "M"

array([nan, 'F', 'M'], dtype=object)

In [89]:
data_spec1['state'] = data_spec1['state'].replace({"AZ": "Arizona", "Cali": "California", "WA": "Washington"})
# State abbreviationsreplaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"

In [90]:
state_counts = data_spec1['state'].value_counts()

# Display the count for each state value to make sure that we do not have abbreviations
for state, count in state_counts.items():
    print(f"{state}: {count}")

California: 331
Oregon: 320
Arizona: 211
Washington: 111
Nevada: 98


In [91]:
data_spec1['education'].unique()
# Replacement of the value Bachelors to Bachelor

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [92]:
data_spec1['education'] = data_spec1['education'].replace({'Bachelors':'Bachelor',})
# Replacement of the value Bachelors to Bachelor

In [93]:
data_spec1['education'].unique() 
# Replacement of the value Bachelors to Bachelor

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [95]:
# Remove the "%" character from the "customer_lifetime_value" column
data_spec1['customer_lifetime_value'] = data_spec1['customer_lifetime_value'].str.replace('%', '')


In [96]:
data_spec1['customer_lifetime_value'].unique() 
# character "%" removed 

array([nan, '697953.59', '1288743.17', ..., '2031499.76', '323912.47',
       '899704.02'], dtype=object)

In [97]:
data_spec1['customer_lifetime_value'] = data_spec1['customer_lifetime_value'].astype(float)

# divide the column customer_lifetime_vlaue by 100 but no after turning into a float

In [98]:
data_spec1['customer_lifetime_value'].unique()
# column column customer_lifetime_vlaue is now a float as we can see below

array([       nan,  697953.59, 1288743.17, ..., 2031499.76,  323912.47,
        899704.02])

In [99]:
data_spec1['customer_lifetime_value'] = data_spec1['customer_lifetime_value']/100
# code to divide by 100

In [100]:
data_spec1['customer_lifetime_value'].unique()
# new result of the division by 100

array([       nan,  6979.5359, 12887.4317, ..., 20314.9976,  3239.1247,
        8997.0402])

In [101]:
data_spec1['customer_lifetime_value'] = data_spec1['customer_lifetime_value'].round(2)
# code to round the result of the division by 100 by 2 digits

In [102]:
data_spec1['customer_lifetime_value'].unique()
# new result of the division by 100 rounded by 2 digits


array([     nan,  6979.54, 12887.43, ..., 20315.  ,  3239.12,  8997.04])

In [103]:
#In vehicle class column replace, "Sports Car", "Luxury SUV" and "Luxury Car" by "Luxury"

data_spec1['vehicle_class'] = data_spec1['vehicle_class'].replace({"Sports Car":"Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"})


In [106]:
data_spec1['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [107]:
data_spec1.dtypes
#Customer lifetime value should be numeric , as we can see below it is a float due to the code performed above in line 97 

data_spec1['customer_lifetime_value'] = data_spec1['customer_lifetime_value'].astype(float

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

In [123]:
data_spec1['number_of_open_complaints'].unique()

array(['A', 'C', 'B', 'D', 'F', 'E', nan], dtype=object)

In [124]:
#the name number_of_open complaints suggests that this variable is a float or numeric but we can see above that is an object.

data_spec1['number_of_open_complaints'] = data_spec1['number_of_open_complaints'].replace({"A": 0,"B": 1, "C":2,"D":3,"E": 4, "F":5})

In [125]:
data_spec1['number_of_open_complaints'].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [126]:
data_spec1.dtypes

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

## Exercise 4: Dealing with Null values

In [128]:
# Assuming you have already loaded your data into the 'data_spec1' DataFrame

# Identify columns with null values
null_columns = data_spec1.columns[data_spec1.isnull().any()]

# Count the number of null values (NaN) in each column
null_counts = data_spec1[null_columns].isnull().sum()

# Print the columns with null values and the number of null values in each
for column, count in null_counts.items():
    print(f"Column '{column}' has {count} null values (NaN).")




Column 'customer' has 2937 null values (NaN).
Column 'state' has 2937 null values (NaN).
Column 'gender' has 3054 null values (NaN).
Column 'education' has 2937 null values (NaN).
Column 'customer_lifetime_value' has 2940 null values (NaN).
Column 'income' has 2937 null values (NaN).
Column 'monthly_premium_auto' has 2937 null values (NaN).
Column 'number_of_open_complaints' has 2937 null values (NaN).
Column 'policy_type' has 2937 null values (NaN).
Column 'vehicle_class' has 2937 null values (NaN).
Column 'total_claim_amount' has 2937 null values (NaN).


Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers using `applymap()`.

In [140]:
# List of columns to check for NaN values created
columns_to_check = [
    "customer",
    "state",
    "gender",
    "education",
    "customer_lifetime_value",
    "income",
    "monthly_premium_auto",
    "number_of_open_complaints",
    "policy_type",
    "vehicle_class",
    "total_claim_amount",
]

# To drop rows with NaN values it was used the dropna method with the subset parameter to drop rows that have NaN values
data_spec1 = data_spec1.dropna(subset=columns_to_check)

# The data_spec1 now contains rows with NaN values in the specified columns dropped.


In [141]:
data_spec1

customer       state gender             education  \
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
5     OC83172      Oregon      F              Bachelor   
...       ...         ...    ...                   ...   
1066  TM65736      Oregon      M                Master   
1067  VJ51327  California      F  High School or Below   
1068  GS98873     Arizona      F              Bachelor   
1069  CW49887  California      F                Master   
1070  MY31220  California      F               College   

      customer_lifetime_value   income  monthly_premium_auto  \
1                     6979.54      0.0                  94.0   
2                    12887.43  48767.0                 108.0   
3                     7645.86      0.0                 106.0   
4                     5363.08  36357.0                  68.0   
5                     8256.30  62902.0                  69.0   
...                       ...      ...                   ...   
1066                  3059.55  38644.0                  78.0   
1067                 20315.00  63209.0                 102.0   
1068                  3239.12  16061.0                  88.0   
1069                  4626.80  79487.0                 114.0   
1070                  8997.04  54230.0                 112.0   

      number_of_open_complaints     policy_type  vehicle_class  \
1                           0.0   Personal Auto  Four-Door Car   
2                           0.0   Personal Auto   Two-Door Car   
3                           0.0  Corporate Auto            SUV   
4                           0.0   Personal Auto  Four-Door Car   
5                           0.0   Personal Auto   Two-Door Car   
...                         ...             ...            ...   
1066                        1.0   Personal Auto  Four-Door Car   
1067                        2.0   Personal Auto            SUV   
1068                        0.0   Personal Auto  Four-Door Car   
1069                        0.0    Special Auto            SUV   
1070                        0.0   Personal Auto   Two-Door Car   

      total_claim_amount  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
5             159.383042  
...                  ...  
1066          361.455219  
1067          207.320041  
1068          633.600000  
1069          547.200000  
1070          537.600000  

[952 rows x 11 columns]

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [ ]:
# Your code here

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here